name: HACKATHON
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.1
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - colorama=0.4.3
  - cycler=0.10.0
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - freetype=2.10.0
  - imagecodecs-lite=2019.12.3
  - importlib_metadata=1.5.0
  - intel-openmp=2019.4
  - ipykernel=5.1.4
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.16.0
  - jinja2=2.11.1
  - jpeg=9c
  - jsonschema=3.2.0
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - kiwisolver=1.1.0
  - libclang=9.0.1
  - libpng=1.6.37
  - libsodium=1.0.17
  - libtiff=4.1.0
  - lz4-c=1.8.3
  - markupsafe=1.1.1
  - matplotlib
  - matplotlib-base
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.0
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - notebook=6.0.3
  - numpy=1.17.4
  - numpy-base=1.17.4
  - olefile=0.46
  - openssl=1.1.1d
  - pandas=0.25.3
  - pandoc=2.9.2
  - pandocfilters=1.4.2
  - parso=0.6.1
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pims=0.4.1
  - pip=20.0.2
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - pygments=2.5.2
  - pyparsing=2.4.6
  - pyqt=5.12.3
  - pyrsistent=0.14.11
  - python=3.7.4
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pyzmq=19.0.0
  - qt=5.12.5
  - qtconsole=4.6.0
  - scipy=1.3.1
  - send2trash=1.5.0
  - setuptools=45.2.0
  - six=1.14.0
  - slicerator=1.0.0
  - sqlite
  - terminado=0.8.3
  - testpath=0.4.4
  - tifffile=2020.2.16
  - tk=8.6.10
  - tornado=6.0.3
  - traitlets=4.3.3
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xz=5.2.4
  - zeromq=4.3.2
  - zipp=3.0.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1

